// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.0.4
// - protoc             v5.28.3
// source: blog/blog.proto

package blog

import (
	context "context"
	pot "github.com/afikrim/pot"
	binder "github.com/afikrim/pot/binder"
	option "github.com/afikrim/pot/binder/option"
	errors "github.com/afikrim/pot/errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the pot package it is being compiled against.
var _ = new(context.Context)
var _ = new(http.Server)
var _ = errors.ErrGeneralBadRequest
var _ = new(pot.ServiceDescriptor)
var _ = new(binder.RequestDecoder)
var _ = new(option.Options)

const (
	Operation_BlogService_CreateBlog = "/blog.BlogService/CreateBlog"
	Operation_BlogService_DeleteBlog = "/blog.BlogService/DeleteBlog"
	Operation_BlogService_ReadBlog   = "/blog.BlogService/ReadBlog"
	Operation_BlogService_UpdateBlog = "/blog.BlogService/UpdateBlog"
)

type BlogServiceHTTPServer interface {
	CreateBlog(ctx context.Context, in *CreateBlogRequest) (*CreateBlogResponse, error)
	DeleteBlog(ctx context.Context, in *DeleteBlogRequest) (*emptypb.Empty, error)
	ReadBlog(ctx context.Context, in *ReadBlogRequest) (*ReadBlogResponse, error)
	UpdateBlog(ctx context.Context, in *UpdateBlogRequest) (*UpdateBlogResponse, error)
}

func RegisterBlogServiceHTTPServer(srv BlogServiceHTTPServer) http.Handler {
	return pot.RegisterService(&_BlogService_HTTP_ServiceDesc, srv)
}

func _BlogService_CreateBlog0_HTTP_Handler(ctx context.Context, srv interface{}, dec pot.DecoderFunc, middleware pot.MiddlewareFunc) (interface{}, error) {
	in := new(CreateBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if middleware == nil {
		return srv.(BlogServiceHTTPServer).CreateBlog(ctx, in)
	}
	h := middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceHTTPServer).CreateBlog(ctx, req.(*CreateBlogRequest))
	})
	return h(ctx, in)
}

func _BlogService_ReadBlog0_HTTP_Handler(ctx context.Context, srv interface{}, dec pot.DecoderFunc, middleware pot.MiddlewareFunc) (interface{}, error) {
	in := new(ReadBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if middleware == nil {
		return srv.(BlogServiceHTTPServer).ReadBlog(ctx, in)
	}
	h := middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceHTTPServer).ReadBlog(ctx, req.(*ReadBlogRequest))
	})
	return h(ctx, in)
}

func _BlogService_UpdateBlog0_HTTP_Handler(ctx context.Context, srv interface{}, dec pot.DecoderFunc, middleware pot.MiddlewareFunc) (interface{}, error) {
	in := new(UpdateBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if middleware == nil {
		return srv.(BlogServiceHTTPServer).UpdateBlog(ctx, in)
	}
	h := middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceHTTPServer).UpdateBlog(ctx, req.(*UpdateBlogRequest))
	})
	return h(ctx, in)
}

func _BlogService_DeleteBlog0_HTTP_Handler(ctx context.Context, srv interface{}, dec pot.DecoderFunc, middleware pot.MiddlewareFunc) (interface{}, error) {
	in := new(DeleteBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if middleware == nil {
		return srv.(BlogServiceHTTPServer).DeleteBlog(ctx, in)
	}
	h := middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceHTTPServer).DeleteBlog(ctx, req.(*DeleteBlogRequest))
	})
	return h(ctx, in)
}

var _BlogService_HTTP_ServiceDesc = pot.ServiceDescriptor{
	ServiceName: "blog.BlogService",
	HandlerType: (*BlogServiceHTTPServer)(nil),
	Methods: []pot.MethodDescriptor{
		{
			MethodName: "CreateBlog",
			HttpMethod: "POST",
			HttpPath:   "/v1/blog",
			Handler:    _BlogService_CreateBlog0_HTTP_Handler,
		},
		{
			MethodName: "ReadBlog",
			HttpMethod: "GET",
			HttpPath:   "/v1/blog/{id}",
			Handler:    _BlogService_ReadBlog0_HTTP_Handler,
		},
		{
			MethodName: "UpdateBlog",
			HttpMethod: "PUT",
			HttpPath:   "/v1/blog/{id}",
			Handler:    _BlogService_UpdateBlog0_HTTP_Handler,
		},
		{
			MethodName: "DeleteBlog",
			HttpMethod: "DELETE",
			HttpPath:   "/v1/blog/{id}",
			Handler:    _BlogService_DeleteBlog0_HTTP_Handler,
		},
	},
}

type BlogServiceHTTPClient interface {
	CreateBlog(ctx context.Context, in *CreateBlogRequest, opts ...option.Option) (*CreateBlogResponse, error)
	DeleteBlog(ctx context.Context, in *DeleteBlogRequest, opts ...option.Option) (*emptypb.Empty, error)
	ReadBlog(ctx context.Context, in *ReadBlogRequest, opts ...option.Option) (*ReadBlogResponse, error)
	UpdateBlog(ctx context.Context, in *UpdateBlogRequest, opts ...option.Option) (*UpdateBlogResponse, error)
}

type BlogServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewBlogServiceHTTPClient(client *http.Client) BlogServiceHTTPClient {
	return &BlogServiceHTTPClientImpl{client}
}

func (c *BlogServiceHTTPClientImpl) CreateBlog(ctx context.Context, in *CreateBlogRequest, opts ...option.Option) (*CreateBlogResponse, error) {
	out := new(CreateBlogResponse)
	pattern := "/v1/blog"
	req, err := http.NewRequest("POST", pattern, nil)
	if err != nil {
		return nil, err
	}
	if err = binder.NewRequestEncoder(req, opts...).Bind(in); err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	res, err := c.cc.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	dec := &binder.ResponseDecoder{Response: res}
	if err := errors.ErrorMap[res.StatusCode]; err != nil {
		customErr := new(errors.Error)
		if err := dec.BindBody(customErr); err != nil {
			return nil, err
		}
		return nil, customErr
	}
	if err := dec.BindBody(out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *BlogServiceHTTPClientImpl) DeleteBlog(ctx context.Context, in *DeleteBlogRequest, opts ...option.Option) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	pattern := "/v1/blog/{id}"
	req, err := http.NewRequest("DELETE", pattern, nil)
	if err != nil {
		return nil, err
	}
	if err = binder.NewRequestEncoder(req, opts...).Bind(in); err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	res, err := c.cc.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	dec := &binder.ResponseDecoder{Response: res}
	if err := errors.ErrorMap[res.StatusCode]; err != nil {
		customErr := new(errors.Error)
		if err := dec.BindBody(customErr); err != nil {
			return nil, err
		}
		return nil, customErr
	}
	if err := dec.BindBody(out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *BlogServiceHTTPClientImpl) ReadBlog(ctx context.Context, in *ReadBlogRequest, opts ...option.Option) (*ReadBlogResponse, error) {
	out := new(ReadBlogResponse)
	pattern := "/v1/blog/{id}"
	req, err := http.NewRequest("GET", pattern, nil)
	if err != nil {
		return nil, err
	}
	if err = binder.NewRequestEncoder(req, opts...).Bind(in); err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	res, err := c.cc.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	dec := &binder.ResponseDecoder{Response: res}
	if err := errors.ErrorMap[res.StatusCode]; err != nil {
		customErr := new(errors.Error)
		if err := dec.BindBody(customErr); err != nil {
			return nil, err
		}
		return nil, customErr
	}
	if err := dec.BindBody(out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *BlogServiceHTTPClientImpl) UpdateBlog(ctx context.Context, in *UpdateBlogRequest, opts ...option.Option) (*UpdateBlogResponse, error) {
	out := new(UpdateBlogResponse)
	pattern := "/v1/blog/{id}"
	req, err := http.NewRequest("PUT", pattern, nil)
	if err != nil {
		return nil, err
	}
	if err = binder.NewRequestEncoder(req, opts...).Bind(in); err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	res, err := c.cc.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	dec := &binder.ResponseDecoder{Response: res}
	if err := errors.ErrorMap[res.StatusCode]; err != nil {
		customErr := new(errors.Error)
		if err := dec.BindBody(customErr); err != nil {
			return nil, err
		}
		return nil, customErr
	}
	if err := dec.BindBody(out); err != nil {
		return nil, err
	}
	return out, nil
}
